from PyQt6.QtWidgets import *
from db_handler import DBHandler
from contact import Contact
from PyQt6.QtGui import *

class AddContact(QWidget):
    def __init__(self) -> None:
        super().__init__()
    
        self.setWindowTitle("Create Contacts")
        self.setWindowIcon(QIcon('contact.png'))    
        
        self.h_box = QHBoxLayout()
        self.save = QPushButton("Save")
        self.clear = QPushButton("clear")
        self.cancel = QPushButton("Cancel")
        self.save.setStyleSheet("background: green")
        self.clear.setStyleSheet("background: blue")
        self.cancel.setStyleSheet("background: red")
        self.h_box.addWidget(self.cancel)
        self.h_box.addWidget(self.save)
        self.h_box.addWidget(self.clear)

        self.h_button_born = QHBoxLayout()
        self.day = QComboBox()
        self.day.addItems([str(i) for i in range(1,32)])
        self.month = QComboBox()
        self.month.addItems(["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])
        self.year = QComboBox()
        self.year.addItems(str(i) for i in range(1950,2015))
        self.h_button_born.addWidget(self.day)
        self.h_button_born.addWidget(self.month)
        self.h_button_born.addWidget(self.year)

        self.v_box = QVBoxLayout()
        self.first = QLineEdit()
        self.first.setPlaceholderText("Enter first name...")
        self.v_box.addWidget(self.first)
        self.last = QLineEdit()
        self.last.setPlaceholderText("Enter last name...")
        self.v_box.addWidget(self.last)
        self.gender = QComboBox()
        self.gender.addItems(['Male','Female'])
        self.v_box.addWidget(self.gender)
        self.v_box.addLayout(self.h_button_born)
    
        self.company = QLineEdit()
        self.company.setPlaceholderText("Enter Company...")
        self.v_box.addWidget(self.company)
        self.phone = QLineEdit()
        self.phone.setPlaceholderText("Enter phone number...")
        self.v_box.addWidget(self.phone)
        self.email = QLineEdit()
        self.email.setPlaceholderText("Enter email...")
        self.v_box.addWidget(self.email)
        self.social = QLineEdit()
        self.social.setPlaceholderText("Enter social...")
        self.v_box.addWidget(self.social)
        self.link = QLineEdit()
        self.link.setPlaceholderText("Enter link...")
        self.v_box.addWidget(self.link)
        self.country = QLineEdit()
        self.country.setPlaceholderText("Enter Country...")
        self.v_box.addWidget(self.country)
        self.city = QLineEdit()
        self.city.setPlaceholderText("Enter city...")
        self.v_box.addWidget(self.city)
        self.street = QLineEdit()
        self.street.setPlaceholderText("Enter street...")
        self.v_box.addWidget(self.street)
        self.home = QLineEdit()
        self.home.setPlaceholderText("Enter home number...") 
        self.v_box.addWidget(self.home)
        self.v_box.addLayout(self.h_box)
        self.setLayout(self.v_box)
        self.style()
        self.save.clicked.connect(self.Save_contact)
        self.clear.clicked.connect(self.Clear_all)
        self.cancel.clicked.connect(self.close)

    def Clear_all(self):
        self.first.clear()
        self.last.clear()
        self.gender.setCurrentIndex(0)
        self.day.setCurrentIndex(0)
        self.month.setCurrentIndex(0)
        self.year.setCurrentIndex(0)
        self.company.clear()
        self.phone.clear()
        self.email.clear()
        self.social.clear()
        self.link.clear()
        self.country.clear()
        self.city.clear()
        self.street.clear()
        self.home.clear()

    def style(self):
        self.first.setStyleSheet("background-color: lightblue")
        self.last.setStyleSheet("background-color: lightblue")
        self.gender.setStyleSheet("background-color: lightblue")
        self.day.setStyleSheet("background-color: lightblue")
        self.month.setStyleSheet("background-color: lightblue")
        self.year.setStyleSheet("background-color: lightblue")
        self.company.setStyleSheet("background-color: lightblue")
        self.phone.setStyleSheet("background-color: lightblue")
        self.email.setStyleSheet("background-color: lightblue")
        self.social.setStyleSheet("background-color: lightblue")
        self.link.setStyleSheet("background-color: lightblue")
        self.country.setStyleSheet("background-color: lightblue")
        self.city.setStyleSheet("background-color: lightblue")
        self.street.setStyleSheet("background-color: lightblue")
        self.home.setStyleSheet("background-color: lightblue")

    def Save_contact(self): 
        db = DBHandler()
        day = self.day.currentIndex() + 1
        month = self.month.itemText()
        year = self.year.itemText()
        first = self.first.text()
        last = self.last.text()
        gender = self.gender.currentText()
        company = self.company.text()
        c = Contact(first,last,gender,day,month,year,company)
        phone = self.phone.text()
        phone = phone.split(",")
        for i in phone:
            c.add_phone(i)
        
        email = self.email.text()
        email = email.split(",")
        for i in email:
            c.add_email(i)
        home = int(self.home.text())
        country = self.country.text()
        city = self.city.text()
        street = self.street.text()
        c.add_address(country,city,street,home)
        social = self.social.text()
        link = self.link.text()
        c.add_social(social,link)
        db.create_contact(c)

        sucs = QMessageBox()
        sucs.setWindowTitle("Save")
        sucs.setText("Success")
        sucs.setStandardButtons(QMessageBox.StandardButton.Ok)
        sucs.setIcon(QMessageBox.Icon.Information)
        self.Clear_all()
        sucs.exec()
        

   

